# Default values for allrest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
registryLocation: "registry.digitalocean.com/registry-062023"
dbUsername: "xxxxx"
dbPassword: "xxxxx"
dbUrl: "xxxxx"
doSpaceUrl: "xxxx"
doSpaceAccessKey: "xxxx"
doSpaceSecretKey: "xxxx"
doSpaceRegion: "xxxx"

# Service Specific Values
allrest_services:
  allrest-pdfgen: 
      name: allrest-pdfgen
      env:
        SPRING_SECURITY_USER_NAME: "username"
        SPRING_SECURITY_USER_PASSWORD: "password"
      envSecretName: db-user-pass
      envFrom:
        DB_USERNAME: "username"
        DB_PASSWORD: "password"
        DB_URL: "url"
        SPACE_URL: "do.space.url"
        SPACE_ACCESS_KEY: "do.space.access-key"
        SPACE_SECRET_KEY: "do.space.secret-key"
        SPACE_REGION: "do.space.region"
      imagename: allrest-pdfgen
      imagePullSecrets: registry-062023
      versionTag: "latest"
      port: 8080
      targetPort: 8080
