apiVersion: v1
data:
  appsettings.json: |
    {
      "Urls": "{{ .Values.Urls }}",
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Hangfire": "Information",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "{{ .Values.allowedHosts }}",
      "ConnectionStrings": {
        "AllRestaurantsMySQL": "server={{ .Values.appSettings.secret }};uid={{ .Values.appSettings.secret }};pwd={{ .Values.appSettings.secret }};database={{ .Values.appSettings.secret }};port=25060;AllowUserVariables=True;CharSet=utf8;",
        "HangfireMySQL": "server={{ .Values.appSettings.secret }};uid={{ .Values.appSettings.secret }};pwd={{ .Values.appSettings.secret }};database={{ .Values.appSettings.secret }};port=25060;AllowUserVariables=True;CharSet=utf8;"
      },
      "AppSettings": {
        "Secret": "{{ .Values.appSettings.secret }}",
        "ServerKey": "{{ .Values.appSettings.serverKey }}",
        "SenderId": "{{ .Values.appSettings.senderId }}",
        "SendGridKey": "{{ .Values.appSettings.sendGridKey }}"
      },
      "AllRestaurantsAuth": {
        "grant_type": "{{ .Values.auth.grant_type }}",
        "client_id": "{{ .Values.auth.client_id }}",
        "client_secret": "{{ .Values.auth.client_secret }}"
      },
      "LettuceEncrypt": {
        "AcceptTermsOfService": true,
        "DomainNames": [
          "{{ .Values.le.domainNames }}"
        ],
        "EmailAddress": "{{ .Values.le.emailAddress }}"
      }
    }
kind: ConfigMap
metadata:
  name: cm-appsettings-api
