# Default values for allrest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
registryLocation: "registry.digitalocean.com/registry-062023"

# Service Specific Values
allrest_services:            
  alltm-admin-panel: 
      name: alltm-admin-panel
      imagename: alltm-admin-panel
      imagePullSecrets: registry-062023
      versionTag: "latest"
      port: 80
      ingressUrl: "adminpanel.allrestaurants.eu"

