# Default values for allrest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
registryLocation: "registry.digitalocean.com/allrest-container-registry"

# Service Specific Values
allrest_services:
  alltm-api: 
      name: alltm-api
      imagename: alltm-api
      imagePullSecrets: allrest-container-registry
      configmap: cm-appsettings-api
      versionTag: "latest"
      port: 8080
      targetPort: 8080      
      ingressUrl: "api.allrestaurants.eu"
