apiVersion: v1
stringData:
  password: {{ .Values.dbPassword }}
  url: jdbc:mysql://{{ .Values.dbUrl }}:25060/allrest
  username: {{ .Values.dbUsername }}
kind: Secret
metadata:
  name: db-user-pass
type: Opaque

