apiVersion: v1
stringData:
  password: {{ .Values.dbPassword }}
  url: jdbc:mysql://{{ .Values.dbUrl }}:25060/allrest
  username: {{ .Values.dbUsername }}
  do.space.url: {{ .Values.doSpaceUrl }}
  do.space.access-key: {{ .Values.doSpaceAccessKey }}
  do.space.secret-key: {{ .Values.doSpaceSecretKey }}
  do.space.region: {{ .Values.doSpaceRegion }}
kind: Secret
metadata:
  name: db-user-pass
type: Opaque

