{{- range $services := .Values.allrest_services}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $services.name }}
    app-id: {{ $.Chart.Name }}
    {{- if $services.extraLabels }}
    {{- range $name, $value := $services.extraLabels }}
    {{ $name }}: {{ $value }}
    {{- end }}
    {{- end }}
  name: {{ $services.name }}
spec:
  replicas: {{ $services.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ $services.name }}
  template:
    metadata:
      labels:
        app: {{ $services.name }}
    spec:
      containers:
      - name: {{ $services.name }}
        {{- if or $services.env $services.envSecretName }}
        env:
        {{- if $services.env }}
        {{- range $name, $value := $services.env }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if $services.envSecretName }}
        {{- range $name, $value := $services.envFrom }}
        - name: {{ $name }}
          valueFrom:
            secretKeyRef:
              key: {{ $value }}
              name: {{ $services.envSecretName }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if $services.repo }}
        image: {{ $services.repo }}/{{ $services.imagename }}:{{ $services.versionTag }}
        {{- else }}
        image: {{ $.Values.registryLocation }}/{{ $services.imagename }}:{{ $services.versionTag }}
        {{- end }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ $services.port }}
          protocol: TCP
        resources:
          requests:
            cpu: "3.5"
            memory: "6Gi"
          limits:
            cpu: "6"
            memory: "10Gi"
        {{- if or $services.configmap $services.googleCredentials }}
        volumeMounts:
        {{- if $services.configmap }}
        - name: mnt
          mountPath: {{ $services.mountPath }}
          subPath: {{ $services.subPath }}
        {{- end }}
        {{- if $services.googleCredentials }}
        - name: google-credentials
          readOnly: true
          mountPath: /var/www/storage/app
        {{- end }}
        {{- end }}
      volumes:
      {{- if $services.configmap }}
      - name: mnt
        configMap:
          name: {{ $services.configmap }}
      {{- end }}
      {{- if $services.googleCredentials }}
      - name: google-credentials
        secret:
          secretName: google-sitemap-key
      {{- end }}
{{- end }}
