# Default values for allrest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
registryLocation: "registry.digitalocean.com/registry-062023"

# Service Specific Values
allrest_services:
  allsupplier-api:
    name: allsupplier-api
    imagename: allsupplier-api
    repo: registry.digitalocean.com/registry-062023
    configmap: cm-php-fpm
    mountPath: "/etc/php/8.1/fpm/pool.d/www.conf"
    subPath: "www.conf"
    imagePullSecrets: registry-062023
    versionTag: "latest"
    port: 80
    ingressUrl: "www.allrestaurants.eu"
